# Generated by Django 2.0.3 on 2018-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(blank=True, default='', max_length=50)),
                ('pet_type', models.CharField(blank=True, choices=[('C', 'Cat'), ('D', 'Dog'), ('P', 'Parrot')], max_length=50)),
                ('pet_location', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
