# Generated by Django 2.0.4 on 2018-04-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180401_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_age',
            field=models.CharField(blank=True, choices=[('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_breed',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_size',
            field=models.CharField(blank=True, choices=[('XSmall', 'XSmall'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'XLarge')], max_length=50),
        ),
    ]
