# Generated by Django 2.0.4 on 2018-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180403_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(default='No Name', max_length=50),
        ),
    ]
