# Generated by Django 2.0.4 on 2018-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180413_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_housetrained',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_spayed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_specialcare',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_vaccinated',
            field=models.NullBooleanField(),
        ),
    ]
