# Generated by Django 2.0.4 on 2018-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180416_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(default='pet_images/default_pet_photo.jpg', upload_to='pet_images'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='super_photo',
            field=models.ImageField(default='super_images/default_super_photo.jpg', upload_to='super_images'),
        ),
    ]
