# Generated by Django 2.0.4 on 2018-04-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180417_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='images/default_photo.jpg', upload_to='images')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(default='images/default_photo.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='super_photo',
            field=models.ImageField(default='images/default_photo.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_gallery', to='app.Gallery'),
        ),
    ]
