# Generated by Django 2.0.4 on 2018-04-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180418_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
