# Generated by Django 2.0.4 on 2018-04-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180418_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(default='pet_images/default_photo.jpg', upload_to='pet_images'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='super_photo',
            field=models.ImageField(default='super_images/default_photo.jpg', upload_to='super_images'),
        ),
    ]
