# Generated by Django 2.0.4 on 2018-04-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180419_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
