# Generated by Django 2.0.4 on 2018-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180419_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
