# Generated by Django 2.0.4 on 2018-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180428_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animaltype',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Parrot', 'Parrot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
