# Generated by Django 2.0.4 on 2018-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180518_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.NullBooleanField(default=False),
        ),
    ]
