# Generated by Django 2.0.4 on 2018-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180518_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=50)),
                ('date_published', models.DateField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
