# Generated by Django 2.0.4 on 2018-05-20 13:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='articles/article_default_image.jpg', upload_to=app.models.article_directory_path),
        ),
    ]
