# Generated by Django 2.0.4 on 2018-05-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_article_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
