# Generated by Django 2.0.4 on 2018-05-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='gallery',
        ),
        migrations.AddField(
            model_name='picture',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pet'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
