# Generated by Django 2.0.4 on 2018-05-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180520_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='image',
        ),
    ]
