# Generated by Django 2.0.4 on 2018-05-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20180520_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='Photo',
        ),
    ]
