# Generated by Django 2.0.5 on 2018-05-20 23:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20180520_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(default='pets/pet_default_image.jpg', upload_to=app.models.pet_directory_path),
        ),
    ]
