# Generated by Django 2.0.4 on 2018-05-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_adopterinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopterinfo',
            name='adopted_pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='adopter_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.AdopterInfo'),
        ),
    ]
