# Generated by Django 2.0.4 on 2018-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180527_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopterinfo',
            name='date_adopted',
            field=models.DateField(auto_now=True),
        ),
    ]
